/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test.test.Forms;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import org.apache.commons.codec.digest.DigestUtils;
import org.javalite.activejdbc.Base;
import org.javalite.activejdbc.DB;
import org.javalite.activejdbc.LazyList;
import org.joda.time.DateTime;
import org.joda.time.Months;
import test.test.Models.AdminModel;
import test.test.Models.PegawaiModel;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

    public Object mdl;
    
    /**
     * Creates new form Logina
     */
    public Login() {
        Base.open();
        this.mdl = PegawaiModel.findAll();
        Base.close();
        
        initComponents();
        
        notif();
    }

    public void notif() {
        int i = 0;
        List<Integer> yangHarusDimerahin = new ArrayList<Integer>();
        List<Map> results;
        List<Map> dummyData;
        List<String> IDCheck = new ArrayList<String>();
    
        //                Gaji Berkala
            Base.open();
            results = new DB().all("SELECT DISTINCT(id_pegawai) FROM gaji_berkala");
            Base.close();

            for (Map result : results) {
                Base.open();
                dummyData = new DB().all("SELECT * FROM gaji_berkala WHERE id_pegawai = ? ORDER BY yad desc LIMIT 1", result.get("id_pegawai"));
                Base.close();
                IDCheck.add(dummyData.get(0).get("id_pegawai").toString());
            }
            
            Base.open();
            for (PegawaiModel data : (LazyList<PegawaiModel>) this.mdl) {
                if (IDCheck.contains(data.getString("id")) && cekDeadline(data.getString("yad_gaji"))) {
                    yangHarusDimerahin.add(Integer.parseInt(data.get("id").toString()));
                }

                i++;
            }
            Base.close();

            i = 0;
            
//                Kenaikan Pangkat
            Base.open();
            results = new DB().all("SELECT DISTINCT(id_pegawai) FROM kenaikan_pangkat");
            Base.close();

            for (Map result : results) {
                Base.open();
                dummyData = new DB().all("SELECT * FROM kenaikan_pangkat WHERE id_pegawai = ? ORDER BY yad desc LIMIT 1", result.get("id_pegawai"));
                Base.close();
                IDCheck.add(dummyData.get(0).get("id_pegawai").toString());
            }

            for (PegawaiModel data : (LazyList<PegawaiModel>) this.mdl) {
                if (IDCheck.contains(data.getString("id")) && cekDeadline(data.getString("yad_pangkat"))) {
                    yangHarusDimerahin.add(Integer.parseInt(data.get("id").toString()));
                }

                i++;
            }
            
            if (yangHarusDimerahin.size() > 0) {
                JOptionPane.showMessageDialog(null, "Ada " + yangHarusDimerahin.size() + " pegawai yang harus segera diusulkan");
            }
    }
    
     public boolean cekDeadline(String dateStop) {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-mm-dd");

        Date d1 = null;
        Date d2 = null;

        try {
            Calendar cal = Calendar.getInstance();
            cal.set(Calendar.HOUR_OF_DAY, 0);
            cal.set(Calendar.MINUTE, 0);
            cal.set(Calendar.SECOND, 0);
            cal.set(Calendar.MILLISECOND, 0);
            d1 = cal.getTime();
            d2 = format.parse(dateStop);

            DateTime dt1 = new DateTime(d1);
            DateTime dt2 = new DateTime(d2);

            if (Months.monthsBetween(dt1, dt2).getMonths() <= 3) {
                return true;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pw = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("Username");

        jLabel1.setText("Password");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(user)
                    .addComponent(pw, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        resetForm();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (user.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Form Username Masih Kosong !!!");
        } else if (pw.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Form Password Masih Kosong !!!");
        } else {
            Base.open();
            AdminModel muser = AdminModel.findFirst("username = ? AND password = ?", user.getText(), DigestUtils.md5Hex(pw.getText()));
            Base.close();
            
            if (muser != null) {
                new MenuUtama().setVisible(true);
                
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Username / Password Salah !!!");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resetForm() {
        user.setText("");
        pw.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField pw;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
